### ISSUE TITLE
Add to the README that IPv6 isn't supported

### ISSUE THREAD

**Issue by deviantintegral** [rkosegi/netflow-collector#134]
I got netflow-collector up and running in my OPNSense + victoriametrics setup nicely, but noticed that a bunch of expected traffic flows were missing. It looks like this is because my ISP fully supports IPv6, and many services (such as Google, Cloudflare, etc) also do.

As I'm new to netflow, I then discovered that you need version 9 support for IPv6 flows: https://docs.opnsense.org/manual/netflow.html

Since this isn't obvious to a new reader, it would be nice if the readme said something like "Netflow V5 (IPv4 only)".

**Comment by rkosegi** [comment]
Hi @deviantintegral, thank you for an idea.

PRs are always welcome.

I personally deem this redundant, since "V5 only" is already mentioned in about section on right pane (`Simple Netflow V5 exporter for prometheus`) and also in _How it works_ section (`it uses V5 version for simplicity`).
